#!/usr/bin/env python

import os
import pylast
import sys

network = pylast.LastFMNetwork(api_key=os.environ["LAST_API_KEY"],
                               api_secret=os.environ["LAST_API_SECRET"],
                               username=os.environ["LAST_USERNAME"],
                               password_hash=os.environ["LAST_PASSWORD"])


def main():
    msg_file_path = sys.argv[0]
    with open(msg_file_path, "r") as msg_file:
        msg = msg_file.read().replace('\n', '')

    print "msg is " + msg

    now = network.get_authenticated_user().get_now_playing()

    if now:
        msg += str(now)
        print msg

        with open(msg_file_path, "w") as msg_file:
            msg_file.write(msg)
            msg_file.flush()


if __name__ == '__main__':
    main()
