#!/usr/bin/env python3

import os
import pylast
import sys


def main():
    network = pylast.LastFMNetwork(api_key=os.environ["LAST_API_KEY"])

    track = network.get_user(os.environ["LAST_USERNAME"]).get_now_playing()

    if not track:
        return

    track_str = str(track)

    print("np: " + track_str)

    if len(sys.argv) < 2:
        return

    msg_file_path = sys.argv[1]

    with open(msg_file_path, "r") as msg_file:
        msg = msg_file.read()

    np_msg = msg + "\n\nnp: " + track_str

    with open(msg_file_path, "w") as msg_file:
        msg_file.write(np_msg)


if __name__ == '__main__':
    main()
